import { METADATA } from '../../../shared/const'

export default function Head() {
  return (
    <>
      <title>{`${METADATA.TITLE} : 홈`}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
